// apps/admin/app/components/ShabadDisplay.vue
<script setup lang="ts">
import { X, Pin } from 'lucide-vue-next';

const props = defineProps<{ shabadId: number }>();
const mainVerseId = defineModel<number | null>('mainVerseId', {
  default: null,
});
const emit = defineEmits<{ clear: []; firstLine: [string] }>();

const verses = ref<any[]>([]);
const loading = ref(false);
const info = ref<any>(null);

const RAHAO = /ਰਹਾਉ|रहाउ|rahaau/i;

/** The rahao is the refrain a ragi returns to, and is what a listener
 *  recognises a rendition by — a better default anchor than the opening line,
 *  which may never be sung prominently. */
function findRahao(list: any[]): number | null {
  for (const v of list) {
    const text = [
      v.verse?.unicode,
      v.verse?.gurmukhi,
      ...Object.values(v.transliteration ?? {}),
    ].filter((x) => typeof x === 'string') as string[];
    if (text.some((t) => RAHAO.test(t))) return v.verseId;
  }
  return list[0]?.verseId ?? null;
}

watch(
  () => props.shabadId,
  async (id) => {
    if (!id) return;
    loading.value = true;
    try {
      const res = await fetch(`https://api.banidb.com/v2/shabads/${id}`);
      const json = await res.json();
      verses.value = json.verses ?? [];
      info.value = json.shabadInfo ?? null;
      // Suggest, don't impose — the tagger can click any line to change it.
      if (mainVerseId.value == null)
        mainVerseId.value = findRahao(verses.value);
      const anchor = verses.value.find((v) => v.verseId === mainVerseId.value);
      if (anchor?.transliteration?.english) {
        emit('firstLine', anchor.transliteration.english);
      }
    } catch {
      verses.value = [];
    } finally {
      loading.value = false;
    }
  },
  { immediate: true }
);

function setMain(v: any) {
  mainVerseId.value = v.verseId;
  if (v.transliteration?.english) emit('firstLine', v.transliteration.english);
}

const gurmukhi = (v: any) => v.verse?.unicode ?? v.verse?.gurmukhi ?? '';
</script>

<template>
  <div class="rounded-lg border border-border">
    <div
      class="flex items-start justify-between gap-2 border-b border-border px-3 py-2"
    >
      <div class="min-w-0">
        <p class="text-xs font-medium">Shabad #{{ props.shabadId }}</p>
        <p v-if="info" class="truncate text-[11px] text-muted-foreground">
          {{
            [
              info.writer?.english,
              info.raag?.english,
              info.pageNo ? `Ang ${info.pageNo}` : null,
            ]
              .filter(Boolean)
              .join(' · ')
          }}
        </p>
      </div>
      <button
        class="shrink-0 text-muted-foreground hover:text-foreground"
        title="Unlink"
        @click="emit('clear')"
      >
        <X class="size-3.5" />
      </button>
    </div>

    <p v-if="loading" class="py-8 text-center text-xs text-muted-foreground">
      Loading…
    </p>

    <div v-else class="max-h-80 overflow-y-auto">
      <!-- Any line can be the anchor; clicking swaps it, so a wrong guess is
           one click to fix rather than a re-link. -->
      <button
        v-for="v in verses"
        :key="v.verseId"
        class="flex w-full items-start gap-2 border-b border-border/60 px-3 py-2 text-left last:border-0 hover:bg-accent"
        :class="v.verseId === mainVerseId && 'bg-amber-500/10'"
        :title="v.verseId === mainVerseId ? 'Main verse' : 'Set as main verse'"
        @click="setMain(v)"
      >
        <Pin
          class="mt-1 size-3 shrink-0"
          :class="
            v.verseId === mainVerseId ? 'text-amber-400' : 'text-transparent'
          "
        />
        <span class="min-w-0">
          <span
            class="block text-[15px] leading-relaxed"
            :class="
              v.verseId === mainVerseId ? 'text-amber-300' : 'text-foreground'
            "
          >
            {{ gurmukhi(v) }}
          </span>
          <span class="block text-[11px] text-muted-foreground">{{
            v.transliteration?.english
          }}</span>
        </span>
      </button>
    </div>

    <p
      class="border-t border-border px-3 py-2 text-[11px] text-muted-foreground"
    >
      Click any line to make it the main verse — the one this rendition is known
      by.
    </p>
  </div>
</template>

// apps/admin/src/components/ShabadDisplay.tsx
/**
 * The linked shabad's lines, so the tagger can choose the anchor.
 *
 * People recognise a kirtan rendition by its rahao — the refrain the ragi
 * returns to — not by the shabad's first line, which is why `main_verse_id`
 * exists at all and why it is worth a click rather than a default.
 *
 * The line searched for and clicked is pre-selected, because that is what the
 * tagger was looking for; every other line is one click away here.
 *
 * The whole verse goes back up, not just its id: picking a line is a statement
 * about which line this rendition is known by, and the form has to be able to
 * rename itself and retitle the linked-shabad pill from it. Handing back a bare
 * number left both showing the line that was *searched* long after another had
 * been chosen, which read as the click having done nothing.
 */
import { type ShabadVerse, useShabadText } from '@kp/api';
import { Pin } from 'lucide-react';

import { BANIDB_BASE } from '~/lib/links';
import { cn } from '~/lib/utils';

export function ShabadDisplay({
  shabadId,
  mainVerseId,
  onPick,
}: {
  shabadId: number;
  mainVerseId: number | null;
  onPick: (verse: ShabadVerse) => void;
}) {
  const query = useShabadText(BANIDB_BASE, shabadId);
  const lines = query.data?.verses ?? [];

  if (query.isLoading) {
    return <p className="px-1 py-2 text-sm text-muted-foreground">Loading the shabad…</p>;
  }

  if (query.isError) {
    return (
      <p className="px-1 py-2 text-sm text-muted-foreground">
        Could not reach BaniDB — the link is saved either way.
      </p>
    );
  }

  return (
    <div className="flex max-h-64 flex-col gap-0.5 overflow-y-auto rounded-lg border border-border p-2">
      <p className="px-1 pb-1 text-xs text-muted-foreground">
        Click a line to make it the main verse — the rahao the ragi returns to.
      </p>

      {lines.map((line) => {
        const picked = line.verseId === mainVerseId;
        return (
          /*
           * A plain button rather than the shared one, as the search results
           * are: the ghost variant's `hover:bg-muted` is emitted after any
           * background set here, so the chosen line lost its tint under the
           * pointer that had just chosen it — the one moment it most needed to
           * be visible. The pin carries the state anyway, so hover cannot hide
           * it at all.
           */
          <button
            key={line.verseId}
            type="button"
            aria-pressed={picked}
            title={picked ? 'The main verse' : 'Set as the main verse'}
            onClick={() => onPick(line)}
            className={cn(
              'flex items-start gap-2 rounded-md px-2 py-1.5 text-left hover:bg-accent/50',
              picked && 'bg-primary/10 hover:bg-primary/15'
            )}
          >
            <Pin
              className={cn('mt-1 size-3 shrink-0', picked ? 'text-primary' : 'text-transparent')}
            />
            <span className="flex min-w-0 flex-col gap-0.5">
              <span className={cn('text-sm', picked && 'font-medium text-primary')}>
                {line.verse?.unicode ?? line.verse?.gurmukhi ?? ''}
              </span>
              {line.transliteration?.english ? (
                <span className="text-xs text-muted-foreground">
                  {line.transliteration.english}
                </span>
              ) : null}
              {line.translation?.en?.bdb ? (
                <span className="text-xs text-muted-foreground/70">{line.translation.en.bdb}</span>
              ) : null}
            </span>
          </button>
        );
      })}
    </div>
  );
}
