// apps/player/src/routes/favorites.tsx
/**
 * Saved shabads.
 *
 * Works signed out: favorites live on the device until there is an account to
 * move them into. The list is fetched by id because that is the only shape
 * both modes share.
 */
import { toPlayable, type Playable } from '@kp/core';
import { Button } from '@kp/ui/button';
import { useQuery } from '@tanstack/react-query';

import { ShabadList } from '~/components/ShabadList';
import { useSession } from '~/lib/session';
import { supabase } from '~/lib/supabase';

export function FavoritesRoute() {
  const { favorites, userId, prompt } = useSession();
  const ids = favorites.ids;

  const query = useQuery({
    queryKey: ['favorites', 'rows', ids],
    queryFn: async (): Promise<Playable[]> => {
      if (!ids.length) return [];
      const { data, error } = await supabase.from('shabads').select('*').in('id', ids);
      if (error) throw error;
      const rows = (data ?? []) as Record<string, unknown>[];
      // Ordered by the saved list, not by what Postgres returned: the listener
      // put these in an order and an `in.()` filter does not preserve it.
      const byId = new Map(rows.map((r) => [r.id as string, r]));
      return ids
        .map((id) => byId.get(id))
        .filter(Boolean)
        .map((r) => toPlayable(r as never));
    },
    enabled: ids.length > 0,
  });

  return (
    <section className="flex flex-col gap-4">
      <header>
        <h1 className="font-display text-3xl font-semibold">Saved</h1>
        <p className="text-sm text-muted-foreground">
          {userId
            ? 'Saved to your account.'
            : 'Saved on this device — sign in and they follow you.'}
        </p>
      </header>

      {/* A failed read is not an empty list: "Nothing saved yet" over an
          account with saved shabads reads as losing them. */}
      {favorites.failed || (query.isError && query.data === undefined) ? (
        <div className="flex flex-wrap items-center gap-2">
          <p role="alert" className="text-sm text-destructive">
            Could not load your saved shabads.
          </p>
          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              favorites.retry();
              void query.refetch();
            }}
          >
            Try again
          </Button>
        </div>
      ) : (
        <ShabadList
          items={query.data ?? []}
          loading={query.isLoading}
          empty="Nothing saved yet."
          emptyHint={
            userId
              ? 'Tap the heart on any shabad to keep it here.'
              : 'Tap the heart on any shabad. Sign in to keep them across devices.'
          }
        />
      )}

      {!userId && ids.length > 0 ? (
        <button
          type="button"
          onClick={prompt}
          className="self-start text-sm text-primary hover:underline"
        >
          Sign in to keep these
        </button>
      ) : null}
    </section>
  );
}

// apps/player/app/pages/favorites.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Button } from '@/components/ui/button';
import { chunk } from '~/lib/utils';

const supabase = useSupabaseClient();
const favorites = useFavorites();
const auth = useAuth();

// Fetched from ids rather than from `favorite_shabads`, because the ids are the
// one thing both modes share: signed out they come from localStorage, where the
// account view would return nothing.
//
// `server: false` is not an optimisation, it is the fix for an empty list. The
// ids live in localStorage or behind a session, so the server always computes
// this as zero favorites — and Nuxt then hydrates that payload and, seeing no
// *change* in the watched ids (the client reads localStorage synchronously,
// before the watcher exists), never refetches. Fetching on the client only
// means the first read already has the real ids.
const { data: shabads } = await useAsyncData(
  'favorites',
  async () => {
    if (!favorites.ids.value.length) return [];
    // Batched, because this filter rides in the query string: one request per
    // ~100 ids, where a single request for a few hundred favorites exceeds the
    // gateway's URI limit and fails outright. See `chunk`.
    const batches = await Promise.all(
      chunk(favorites.ids.value).map((batch) =>
        supabase.from('shabads').select('*').in('id', batch)
      )
    );
    const failed = batches.find((b) => b.error);
    if (failed) console.error('favorites failed', failed.error?.message);
    return batches.flatMap((b) => b.data ?? []);
  },
  { server: false, watch: [favorites.ids] }
);

// `in()` returns rows in whatever order Postgres finds them; the ids are held
// newest-first, and that is the order the listener saved them in.
const ordered = computed(() => {
  const rows = shabads.value ?? [];
  const order = favorites.ids.value;
  return [...rows].sort((a, b) => order.indexOf(a.id) - order.indexOf(b.id));
});
</script>

<template>
  <div>
    <SavedHeader />

    <ShabadRow
      v-for="(s, i) in ordered"
      :key="s.id"
      :shabad="s"
      :index="i"
      :list="ordered"
    />
    <EmptyState
      v-if="!ordered.length"
      title="Nothing saved yet"
      hint="Tap the heart on any shabad."
    />

    <!-- Only worth saying once the session is known, and only to guests:
         telling a signed-in listener their favorites are device-local would be
         wrong, and saying it before `ready` would flash it at everyone. -->
    <div
      v-if="auth.ready.value && !auth.user.value"
      class="mt-6 flex flex-wrap items-center gap-3 rounded-lg border border-border p-4"
    >
      <p class="min-w-0 flex-1 text-xs text-muted-foreground">
        These favorites are saved on this device. Sign in and they follow you —
        the list comes across as it is, nothing is lost.
      </p>
      <Button size="sm" variant="outline" @click="auth.prompt()">
        Sign in
      </Button>
    </div>
  </div>
</template>
