// apps/admin/app/components/ShabadSearch.vue
<script setup lang="ts">
import { Search, X } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { ButtonGroup } from '@/components/ui/button-group';
import { Input } from '@/components/ui/input';
import { SELECTED_SEGMENT } from '@/lib/segmented';
import { prettyShabadName } from '~/composables/useShabadName';

const emit = defineEmits<{
  select: [{ shabadId: number; verseId: number | null; firstLine: string }];
}>();

// searchtype 0 is BaniDB's first-letter search and accepts both Gurmukhi and
// the roman keys that map onto it; 7 searches the English translation and
// returns nothing for Gurmukhi input. Punjabi is the default because that is
// how kirtan is looked up — you hear a line and type its initials.
const LANGS = [
  { key: 0, label: 'Punjabi' },
  { key: 7, label: 'English' },
] as const;

// Same-origin proxy in dev — see nuxt.config routeRules.
const base = useRuntimeConfig().public.banidbApiBaseUrl;

const lang = useLocalStorage<number>('kp:shabad-lang', 0);
const q = ref('');
const debounced = refDebounced(q, 300);
const loading = ref(false);
const results = ref<any[]>([]);

/**
 * Typing is GurbaniLipi, the way np-mono's shabad search is.
 *
 * The field keeps the tagger's raw keystrokes and renders them in the
 * GurbaniLipi font, so `mdmA` shows as ਮਦਮਅ while the query still holds the
 * ASCII BaniDB's first-letter search wants. There is no transliteration step,
 * which is the point: nothing can disagree about what was typed, the caret
 * never jumps, and paste, backspace and selection all behave like a normal
 * input because it is one.
 *
 * English search is a different alphabet, so it drops the font and reads as
 * roman.
 */
const gurbaniLipi = computed(() => lang.value === 0);

let generation = 0;

watch([debounced, lang], async () => {
  const term = debounced.value.trim();
  const mine = ++generation;
  if (term.length < 2) {
    results.value = [];
    return;
  }
  loading.value = true;
  try {
    const res = await fetch(
      `${base}/search/${encodeURIComponent(term)}?searchtype=${lang.value}`
    );
    const json = await res.json();
    if (mine !== generation) return;
    results.value = (json.verses ?? []).slice(0, 12);
  } catch {
    if (mine === generation) results.value = [];
  } finally {
    if (mine === generation) loading.value = false;
  }
});

function choose(v: any) {
  // The line the tagger searched for and clicked is a stronger signal than any
  // heuristic — they were looking for that line. It becomes the anchor, and
  // any other line is one click away in the display below.
  emit('select', {
    shabadId: v.shabadId,
    verseId: typeof v.verseId === 'number' ? v.verseId : null,
    firstLine: prettyShabadName(v.transliteration?.english ?? ''),
  });
  q.value = '';
  results.value = [];
}

const gurmukhi = (v: any) => v.verse?.unicode ?? v.verse?.gurmukhi ?? '';
</script>

<template>
  <div>
    <ButtonGroup class="mb-2" aria-label="Search language">
      <Button
        v-for="l in LANGS"
        :key="l.key"
        size="sm"
        variant="outline"
        :aria-pressed="lang === l.key"
        :class="['px-2 text-[11px]', SELECTED_SEGMENT]"
        @click="lang = l.key"
      >
        {{ l.label }}
      </Button>
    </ButtonGroup>

    <div class="relative">
      <Search
        class="pointer-events-none absolute top-1/2 left-3 z-10 size-3.5 -translate-y-1/2 text-muted-foreground"
      />
      <Input
        v-model="q"
        placeholder="Search a shabad"
        class="bg-card py-2 pr-16 pl-9"
        :class="gurbaniLipi ? 'font-gurmukhi text-xl' : 'text-[15px]'"
      />
      <div class="absolute top-1/2 right-1 flex -translate-y-1/2 items-center">
        <Button
          v-if="q"
          variant="ghost"
          size="icon-sm"
          class="size-7 text-muted-foreground"
          aria-label="Clear the search"
          @click="((q = ''), (results = []))"
        >
          <X class="size-3.5" />
        </Button>
        <GurmukhiKeyboard v-if="gurbaniLipi" v-model="q" />
      </div>
    </div>

    <p v-if="loading" class="mt-2 text-xs text-muted-foreground">Searching…</p>

    <ul
      v-if="results.length"
      class="mt-2 max-h-60 overflow-y-auto rounded-md border border-border"
    >
      <li v-for="v in results" :key="v.verseId">
        <button
          class="w-full border-b border-border px-3 py-2 text-left last:border-0 hover:bg-accent"
          @click="choose(v)"
        >
          <span
            class="block truncate text-[15px] leading-relaxed text-foreground"
          >
            {{ gurmukhi(v) }}
          </span>
          <span class="block truncate text-xs text-muted-foreground">
            {{ v.transliteration?.english }}
          </span>
          <span class="block truncate text-[11px] text-muted-foreground/70">
            {{
              [
                v.writer?.english,
                v.raag?.english,
                v.pageNo ? `Ang ${v.pageNo}` : null,
              ]
                .filter(Boolean)
                .join(' · ')
            }}
          </span>
        </button>
      </li>
    </ul>
  </div>
</template>

// packages/ui/src/components/app/shabad-search.tsx
/**
 * Search BaniDB for a line.
 *
 * Shared by the workbench, where it links a shabad to a rendition, and by the
 * player's read-along, where a listener on a live broadcast can look up what
 * they are hearing.
 *
 * Typing is GurbaniLipi. The field keeps raw keystrokes and renders them in the
 * GurbaniLipi font, so `mdmA` shows as ਮਦਮਅ while the query still holds the
 * ASCII BaniDB's first-letter search wants. There is no transliteration step,
 * which is the point: nothing can disagree about what was typed, the caret
 * never jumps, and paste, backspace and selection behave like a normal input
 * because it is one.
 */
import { SEARCH_TYPES, useBaniDbSearch, type BaniDbHit } from "@kp/api"
import { Search, X } from "lucide-react"
import * as React from "react"
import { useLocalStorage } from "usehooks-ts"

import { Button } from "../ui/button"
import { Input } from "../ui/input"
import { GurmukhiKeyboard } from "./gurmukhi-keyboard"
import { cn } from "../../lib/utils"

export interface ShabadPick {
  shabadId: number
  verseId: number
  firstLine: string
  transliteration: string
}

export function ShabadSearch({
  base,
  onSelect,
  placeholder = "Type the first letters…",
  className,
}: {
  base: string
  onSelect: (pick: ShabadPick) => void
  placeholder?: string
  className?: string
}) {
  const [lang, setLang] = useLocalStorage<number>("kp:shabad-lang", 0)
  const [term, setTerm] = React.useState("")

  const query = useBaniDbSearch(base, term, lang)
  const hits = query.data ?? []

  // English search is a different alphabet, so it drops the font and reads as
  // roman.
  const gurbaniLipi = lang === 0

  return (
    <div className={cn("flex flex-col gap-2", className)}>
      <div className="flex items-center gap-1">
        <div className="relative flex-1">
          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={term}
            onChange={(e) => setTerm(e.target.value)}
            placeholder={placeholder}
            aria-label="Search BaniDB"
            className={cn("pl-9 pr-8", gurbaniLipi && "font-gurmukhi text-lg")}
          />
          {term ? (
            <Button
              variant="ghost"
              size="icon-sm"
              aria-label="Clear"
              onClick={() => setTerm("")}
              className="absolute right-1 top-1/2 -translate-y-1/2"
            >
              <X />
            </Button>
          ) : null}
        </div>

        {gurbaniLipi ? <GurmukhiKeyboard value={term} onChange={setTerm} /> : null}
      </div>

      <div className="flex gap-1">
        {SEARCH_TYPES.map((type) => (
          <Button
            key={type.key}
            variant={lang === type.key ? "secondary" : "ghost"}
            size="xs"
            aria-pressed={lang === type.key}
            onClick={() => setLang(type.key)}
          >
            {type.label}
          </Button>
        ))}
      </div>

      {query.isLoading ? (
        <p className="px-1 py-2 text-sm text-muted-foreground">Searching…</p>
      ) : null}

      {query.isError ? (
        <p className="px-1 py-2 text-sm text-muted-foreground">Could not reach BaniDB.</p>
      ) : null}

      {!query.isLoading && term.trim().length >= 2 && !hits.length ? (
        <p className="px-1 py-2 text-sm text-muted-foreground">Nothing matches.</p>
      ) : null}

      <div className="flex flex-col gap-0.5">
        {hits.map((hit: BaniDbHit) => (
          <button
            key={hit.verseId}
            type="button"
            onClick={() =>
              // The line somebody searched for and clicked is a stronger signal
              // than any heuristic — they were looking for that line. It
              // becomes the anchor.
              onSelect({
                shabadId: hit.shabadId,
                verseId: hit.verseId,
                firstLine: hit.verse?.unicode ?? hit.verse?.gurmukhi ?? "",
                transliteration: hit.transliteration?.english ?? "",
              })
            }
            className="rounded-lg px-2 py-2 text-left hover:bg-accent/50"
          >
            <p className="text-sm">{hit.verse?.unicode ?? hit.verse?.gurmukhi}</p>
            <p className="text-xs text-muted-foreground">
              {hit.transliteration?.english}
            </p>
            {hit.writer?.english || hit.raag?.english ? (
              <p className="text-[11px] text-muted-foreground/70">
                {[hit.writer?.english, hit.raag?.english].filter(Boolean).join(" · ")}
              </p>
            ) : null}
          </button>
        ))}
      </div>
    </div>
  )
}
