// apps/player/app/components/AccountButton.vue
<script setup lang="ts">
/**
 * The whole account surface: sign in, or the email with a way out.
 *
 * Deliberately one small control. The player stores nothing about an account
 * beyond what that account has saved, so there is no profile to edit.
 *
 * `compact` is for the saved pages' headers, which is where this has to appear
 * on touch — the mobile tab bar is full at five entries and there is no sidebar
 * to hold it.
 */
import { LogIn, LogOut, User } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

const props = defineProps<{ compact?: boolean }>();

const auth = useAuth();

const trigger = computed(() =>
  props.compact
    ? 'max-w-[11rem] gap-2 px-2 text-xs font-normal text-muted-foreground'
    : 'w-full justify-start gap-3 px-3 text-sm font-normal text-muted-foreground'
);
</script>

<template>
  <!-- `ready` is false through SSR and until the stored session has been read,
       and this renders nothing until then. Showing the signed-out state first
       would flash "Sign in" at someone who is already signed in. -->
  <template v-if="auth.ready.value">
    <DropdownMenu v-if="auth.user.value">
      <DropdownMenuTrigger as-child>
        <Button variant="ghost" :class="trigger">
          <User class="size-[18px] shrink-0" />
          <span class="truncate">{{ auth.user.value.email }}</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start" class="w-56">
        <DropdownMenuLabel
          class="truncate text-xs font-normal text-muted-foreground"
        >
          {{ auth.user.value.email }}
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem @select="auth.signOut()">
          <LogOut class="size-4" /> Sign out
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>

    <Button v-else variant="ghost" :class="trigger" @click="auth.prompt()">
      <LogIn class="size-[18px] shrink-0" />
      Sign in
    </Button>
  </template>
</template>

// apps/player/src/components/AccountButton.tsx
/**
 * The account control, which is a sign-in button until there is a session.
 *
 * Held in its guest state until `loading` clears: flashing an account menu at
 * someone who turns out to be signed out, or the reverse, is worse than a beat
 * of nothing.
 */
import { signOut } from '@kp/api';
import { Avatar, AvatarFallback } from '@kp/ui/avatar';
import { Button } from '@kp/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@kp/ui/dropdown-menu';
import { Link } from '@tanstack/react-router';
import { Heart, ListMusic, LogOut } from 'lucide-react';

import { useSession } from '~/lib/session';
import { supabase } from '~/lib/supabase';

export function AccountButton() {
  const { session, loading, prompt } = useSession();

  if (loading) return <div className="size-8" aria-hidden />;

  if (!session) {
    return (
      <Button variant="ghost" size="sm" onClick={prompt}>
        Sign in
      </Button>
    );
  }

  const email = session.user.email ?? '';
  const initial = email.slice(0, 1).toUpperCase() || '?';

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        render={
          <Button variant="ghost" size="icon" className="rounded-full" aria-label="Account" />
        }>
        <Avatar className="size-7">
          <AvatarFallback className="text-xs">{initial}</AvatarFallback>
        </Avatar>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuLabel className="truncate font-normal text-muted-foreground">
          {email}
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem render={<Link to="/favorites" />}>
          <Heart />
          Saved
        </DropdownMenuItem>
        <DropdownMenuItem render={<Link to="/playlists" />}>
          <ListMusic />
          Playlists
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onSelect={() => void signOut(supabase)}>
          <LogOut />
          Sign out
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
