// apps/player/app/components/LyricsPanel.vue
<script setup lang="ts">
import { X } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { usePlayer } from '~/composables/usePlayer';

const player = usePlayer();
const { shabad, loading, load } = useShabadText();
const open = defineModel<boolean>('open', { default: false });

/**
 * Filling a container rather than floating over the bar.
 *
 * The full-screen player shows the read-along where the artwork was, which is
 * where every phone music player puts lyrics. Same component either way — all
 * the follow-along logic below is the part worth having once — so only the
 * frame changes: no positioning, no border, no shadow, and no close button,
 * because the toggle that opened the view closes it.
 */
const props = defineProps<{ inline?: boolean }>();

// Only tagged segments carry a shabad id — most will not, for a long time.
const shabadId = computed(() => player.current.value?.shabadId ?? null);
const mainVerseId = computed(() => player.current.value?.mainVerseId ?? null);

// `immediate` because the panel is no longer always mounted: the full-screen
// player creates it already open, and a watcher that only answers a *change*
// would then never fetch — the frame appeared with no shabad in it.
watch(
  [open, shabadId],
  () => {
    if (open.value) void load(shabadId.value);
  },
  { immediate: true }
);

const lines = computed(() => shabad.value?.verses ?? []);

// Which line is being sung right now, for an aligned rendition. The timings
// are sparse by design, so falling between two of them — alaap, instrumental,
// katha — is not a miss to paper over: nothing is being sung, and nothing
// should be lit. `find` over fewer than sixty entries is cheap enough to run
// on every `timeupdate`; the array itself is only re-read when the track does.
const timings = computed(() => player.current.value?.lineTimings ?? null);

const singingVerseId = computed(() => {
  const at = player.currentTime.value;
  return (
    timings.value?.find((l) => at >= l.start && at < l.end)?.verse_id ?? null
  );
});

// Aligned renditions follow the singing; everything else — most of the archive
// — keeps holding the one line the tagger pinned, exactly as before.
const highlightId = computed(() =>
  timings.value?.length ? singingVerseId.value : mainVerseId.value
);

// Always the whole shabad, with the sung line lit and scrolled to.
//
// An aligned rendition used to open on the sung line alone — a projector view,
// with the full text one caret away. It reads well and it was the wrong
// default: a shabad is a poem you follow, so the lines already sung and the
// ones coming are the context that makes the lit one mean anything, and a
// single centred line gives a reader no way to see where they are in it. The
// toggle went with it rather than becoming a preference nobody would find.

// Where the scroll goes. Falls back to the tagger's anchor when nothing is
// being sung right now: opening the panel mid-alaap on an aligned rendition
// must still position the reader at the refrain (the old behavior for every
// rendition), not leave them at the top of the shabad — and when the first
// line then lands, the smooth scroll travels from the refrain's neighborhood
// instead of crawling the whole shabad. The VISUAL highlight stays
// `highlightId` alone; a gap still lights nothing.
const anchorId = computed(() => highlightId.value ?? mainVerseId.value);

// A shabad runs well past the height of this panel, so the highlighted line is
// usually below the fold on open. Scroll to it rather than making the reader
// hunt for the line the rendition is actually on.
const anchorEl = ref<HTMLElement | null>(null);
/** The scrolling box itself, so a scroll can be aimed at it and nothing else. */
const panelEl = useTemplateRef<HTMLElement>('panelEl');

// Written through a setter so the template's `:ref` and the clear below agree,
// and so clearing it does not narrow the ref to `null` for the read after the
// await — the render in between is exactly what puts an element back.
function setAnchor(el: HTMLElement | null) {
  anchorEl.value = el;
}

// The panel is the reader's once they scroll it: a listener who scrolled down
// to read a later translation must not be yanked back to the sung line every
// time the singing advances. Wheel and touch mark reader intent (`scroll`
// would also fire for our own scrollIntoView); follow-along resumes after a
// pause, or immediately on reopen.
const READER_HOLD_MS = 8000;
let readerScrolledAt = 0;
function onReaderScroll() {
  readerScrolledAt = Date.now();
}

async function scrollToHighlight(smooth: boolean) {
  if (!open.value || anchorId.value == null) return;
  if (smooth && Date.now() - readerScrolledAt < READER_HOLD_MS) return;
  // Drop the old element first: a timing can name a verse this shabad's text
  // does not contain, and no ref callback would then match to overwrite it.
  setAnchor(null);
  // The cached path fills `lines` on a microtask, so wait for the render that
  // creates the element before reaching for it.
  await nextTick();
  const line = anchorEl.value;
  const box = panelEl.value;
  if (!line || !box) return;
  // Scrolling this panel by hand rather than `scrollIntoView`, which walks up
  // and moves every scrollable ancestor it finds. Inside the desktop player
  // that reached the document itself and slid the entire app — sidebar,
  // transport and all — 173px up the window.
  const lineBox = line.getBoundingClientRect();
  const panelBox = box.getBoundingClientRect();
  box.scrollTo({
    top:
      box.scrollTop +
      (lineBox.top - panelBox.top) -
      (panelBox.height - lineBox.height) / 2,
    behavior: smooth ? 'smooth' : 'auto',
  });
}

watch([lines, open], () => {
  // A fresh open is a request for positioning — any earlier reading pause is
  // over by definition.
  readerScrolledAt = 0;
  void scrollToHighlight(false);
});

// Once per line, not once per tick — `highlightId` only changes when the
// singing moves on. Smooth here and not on open, where the same animation
// would crawl the whole length of the shabad.
watch(highlightId, () => void scrollToHighlight(true));
</script>

<template>
  <aside
    v-if="open"
    ref="panelEl"
    class="overflow-y-auto"
    :class="
      props.inline
        ? 'size-full overscroll-contain'
        : 'absolute right-4 bottom-full left-4 mb-2 max-h-[min(28rem,60svh)] rounded-lg border border-border bg-card shadow-2xl md:left-auto md:w-96'
    "
    @wheel.passive="onReaderScroll"
    @touchmove.passive="onReaderScroll"
  >
    <!-- No title and no writer/raag/ang line any more: the panel is opened
         from a tab that already says "Read along", and what is playing is named
         by the bar and by the full player's own heading — so the header was
         three restatements taking the top of a small scrolling box. What is
         left is the floating panel's way out; inline, the tab that opened this
         closes it. -->
    <div
      v-if="!props.inline"
      class="sticky top-0 z-10 flex justify-end bg-card px-2 pt-2"
    >
      <Button
        variant="ghost"
        size="icon-sm"
        class="size-7 text-muted-foreground"
        aria-label="Close the read-along"
        @click="open = false"
      >
        <X class="size-4" />
      </Button>
    </div>

    <div class="px-4 py-3">
      <p v-if="loading" class="py-8 text-center text-xs text-muted-foreground">
        Loading…
      </p>
      <template v-else>
        <!-- The line is marked the same way the tagger saw the anchor in admin
             — a warm wash and a rule down the side. On an aligned rendition
             that mark walks down the shabad with the singing, so it fades
             rather than jumping; between two timings it is on no line at all,
             which is the point of a gap and not a missing highlight. -->
        <p
          v-for="v in lines"
          :key="v.verseId"
          :ref="
            (el) => {
              if (v.verseId === anchorId) setAnchor(el as HTMLElement);
            }
          "
          class="border-b border-border/60 py-2 transition-colors last:border-0"
          :class="
            v.verseId === highlightId &&
            '-mx-2 rounded-r border-l-2 border-l-primary bg-primary/10 px-2'
          "
        >
          <span
            class="block text-[15px] leading-relaxed"
            :class="
              v.verseId === highlightId ? 'text-primary' : 'text-foreground'
            "
          >
            {{ v.verse?.unicode ?? v.verse?.gurmukhi }}
          </span>
          <span
            class="mt-0.5 block text-xs"
            :class="
              v.verseId === highlightId
                ? 'text-primary/70'
                : 'text-muted-foreground'
            "
          >
            {{ v.transliteration?.english }}
          </span>
          <span
            v-if="v.translation?.en?.bdb"
            class="mt-0.5 block text-xs text-muted-foreground"
          >
            {{ v.translation.en.bdb }}
          </span>
        </p>
      </template>
    </div>
  </aside>
</template>

// apps/player/src/components/LyricsPanel.tsx
/**
 * Read-along.
 *
 * Always the whole shabad, with the sung line lit and scrolled to. An aligned
 * rendition once opened on the sung line alone — a projector view — and it
 * read well but was the wrong default: a shabad is a poem you follow, so the
 * lines already sung and the ones coming are the context that makes the lit
 * one mean anything.
 */
import { highlightVerseId, isAligned } from '@kp/core';
import { useShabadText } from '@kp/api';
import { ShabadSearch } from '@kp/ui/app/shabad-search';
import { Button } from '@kp/ui/button';
import { X } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';

import { usePlayer } from '~/lib/player';
import { BANIDB_BASE } from '~/lib/links';
import { cn } from '~/lib/utils';

/**
 * The panel is the reader's once they scroll it.
 *
 * A listener who scrolled down to read a later translation must not be yanked
 * back to the sung line every time the singing advances. Wheel and touch mark
 * reader intent — `scroll` would also fire for our own scrollIntoView.
 */
const READER_HOLD_MS = 8000;

export function LyricsPanel({ className }: { className?: string }) {
  const current = usePlayer((s) => s.current);
  const position = usePlayer((s) => s.position);

  /**
   * A shabad the listener looked up themselves.
   *
   * Most of the archive is untagged and a broadcast is never tagged at all, so
   * the panel would otherwise be a dead end exactly when somebody most wants it
   * — they are hearing a line right now and want to read along. Cleared when
   * the track changes, because it was chosen for that track.
   */
  const [pick, setPick] = useState<{ trackId: string; shabadId: number } | null>(null);

  // Paired with the track it was chosen for, rather than cleared by an effect
  // on `current?.id`. The effect ran a render *after* the new track arrived, so
  // the panel showed the previous track's shabad for a frame on every skip.
  const lookedUp = pick && pick.trackId === current?.id ? pick.shabadId : null;

  const shabadId = current?.shabadId ?? lookedUp;
  const query = useShabadText(BANIDB_BASE, shabadId);
  const lines = query.data?.verses ?? [];

  // Timings belong to the tagged rendition, so a looked-up shabad lights
  // nothing — there is nothing aligning it to this audio.
  const lit = current?.shabadId ? highlightVerseId(current, position) : null;

  /**
   * Where the scroll goes. Falls back to the tagger's anchor when nothing is
   * being sung: opening mid-alaap on an aligned rendition must still position
   * the reader at the refrain rather than the top of the shabad. The visual
   * highlight stays `lit` alone — a gap lights nothing.
   */
  const anchorId = lit ?? current?.mainVerseId ?? null;

  const panel = useRef<HTMLDivElement>(null);
  const anchor = useRef<HTMLParagraphElement | null>(null);
  const readerScrolledAt = useRef(0);

  const markReaderIntent = useCallback(() => {
    readerScrolledAt.current = Date.now();
  }, []);

  useEffect(() => {
    const box = panel.current;
    const line = anchor.current;
    if (anchorId == null || !box || !line) return;
    if (Date.now() - readerScrolledAt.current < READER_HOLD_MS) return;

    // Aimed at the panel rather than `scrollIntoView`, which walks every
    // scrollable ancestor — inside the phone sheet that scrolled the sheet
    // itself, carrying the artwork and the transport off the top of the screen.
    const top = line.offsetTop - box.clientHeight / 2 + line.clientHeight / 2;
    box.scrollTo({ top: Math.max(0, top), behavior: 'smooth' });
  }, [anchorId]);

  if (!shabadId) {
    return (
      <div className={cn('flex flex-col gap-3 overflow-y-auto p-4', className)}>
        <p className="text-sm text-muted-foreground">
          {current?.isLive
            ? 'Nothing is tagged on a live broadcast — search for the line you are hearing.'
            : 'No shabad linked to this rendition yet. Search for the line you are hearing.'}
        </p>
        <ShabadSearch
          base={BANIDB_BASE}
          onSelect={(chosen) =>
            current && setPick({ trackId: current.id, shabadId: chosen.shabadId })
          }
        />
      </div>
    );
  }

  return (
    <div
      ref={panel}
      onWheel={markReaderIntent}
      onTouchMove={markReaderIntent}
      className={cn('overflow-y-auto px-4 py-3', className)}
    >
      {/* A looked-up shabad is the listener's guess, not a tag — labelled so
          nobody reads it as something the archive asserts. */}
      {!current?.shabadId && lookedUp ? (
        <div className="mb-3 flex items-center gap-2 rounded-lg bg-accent/50 px-3 py-2">
          <p className="flex-1 text-xs text-muted-foreground">
            You looked this up — it is not tagged to this recording.
          </p>
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label="Clear the looked-up shabad"
            onClick={() => setPick(null)}
          >
            <X />
          </Button>
        </div>
      ) : null}

      {query.isLoading ? (
        <p className="py-6 text-center text-sm text-muted-foreground">Loading the shabad…</p>
      ) : null}

      {query.isError ? (
        <p className="py-6 text-center text-sm text-muted-foreground">
          Could not reach BaniDB for this shabad.
        </p>
      ) : null}

      <div className="flex flex-col gap-3">
        {lines.map((line) => {
          const isLit = line.verseId === lit;
          return (
            <p
              key={line.verseId}
              ref={line.verseId === anchorId ? anchor : undefined}
              className={cn(
                'text-base leading-relaxed transition-colors',
                isLit ? 'text-primary' : 'text-muted-foreground'
              )}
            >
              {line.verse?.unicode ?? line.verse?.gurmukhi ?? ''}
              {line.translation?.en?.bdb ? (
                <span className="mt-0.5 block text-xs text-muted-foreground/70">
                  {line.translation.en.bdb}
                </span>
              ) : null}
            </p>
          );
        })}
      </div>

      {/* Unaligned renditions hold the tagger's line rather than following the
          singing. Said once, at the foot, so nobody reads the static highlight
          as a bug. */}
      {lines.length && !isAligned(current) ? (
        <p className="py-4 text-center text-xs text-muted-foreground/60">
          This rendition has no line timings yet — the highlight is the tagged line.
        </p>
      ) : null}
    </div>
  );
}
