// apps/player/app/components/NewPlaylistDialog.vue
<script setup lang="ts">
/**
 * Create a playlist — and, when it was opened from a row menu, drop that shabad
 * into it. That pairing is the point: "add to playlist" with no playlists yet
 * should not be a dead end that makes you go and build one first.
 *
 * Mounted once in app.vue, opened through `usePlaylists().promptNew()`.
 */
import { ref, watch } from 'vue';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';

const playlists = usePlaylists();

const name = ref('');
const message = ref('');
const busy = ref(false);

watch(playlists.newOpen, (open) => {
  if (open) {
    name.value = '';
    message.value = '';
    return;
  }
  // Closing without creating drops the held shabad. Leaving it set would mean
  // the next sign-in reopens this dialog over a pick the listener abandoned.
  playlists.pendingPick.value = null;
});

async function submit() {
  if (busy.value) return;
  const trimmed = name.value.trim();
  if (!trimmed) {
    message.value = 'Give the playlist a name.';
    return;
  }

  busy.value = true;
  try {
    const created = await playlists.create(trimmed);
    if (!created) {
      message.value = 'Could not create that playlist.';
      return;
    }
    const pick = playlists.pendingPick.value;
    if (pick) await playlists.addItem(created.id, pick.id);
    playlists.pendingPick.value = null;
    playlists.newOpen.value = false;
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <Dialog v-model:open="playlists.newOpen.value">
    <DialogContent class="sm:max-w-sm">
      <DialogHeader>
        <DialogTitle>New playlist</DialogTitle>
        <!-- Always rendered, both branches: a DialogContent without a
             description has nothing for aria-describedby to point at. -->
        <DialogDescription>
          <!-- Named, not just "the shabad you picked": after a sign-in detour
               the listener is several steps from the row they tapped. -->
          {{
            playlists.pendingPick.value
              ? `“${playlists.pendingPick.value.name}” goes in as its first track.`
              : 'Add shabads to it from the ⋯ menu on any row.'
          }}
        </DialogDescription>
      </DialogHeader>

      <form @submit.prevent="submit">
        <Input
          v-model="name"
          placeholder="Morning kirtan"
          maxlength="120"
          autofocus
        />
        <p v-if="message" class="mt-2 text-xs text-amber-400">{{ message }}</p>
        <DialogFooter class="mt-4">
          <Button type="submit" :disabled="busy">
            {{ busy ? 'Creating…' : 'Create playlist' }}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>

// apps/player/src/components/NewPlaylistDialog.tsx
/**
 * Create a playlist, optionally holding a shabad to drop into it.
 *
 * Mounted once in the shell rather than per row: a dialog inside the row menu
 * would be one mounted dialog per visible shabad. The pending pick carries its
 * name as well as its id so the dialog can say which shabad it is holding —
 * which matters most when the pick survived a sign-in detour and the listener
 * is several steps from the row they tapped.
 */
import { usePlaylistMutations } from '@kp/api';
import { Button } from '@kp/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@kp/ui/dialog';
import { Input } from '@kp/ui/input';
import { Label } from '@kp/ui/label';
import { useEffect, useState, type FormEvent } from 'react';
import { toast } from 'sonner';

import { useSession } from '~/lib/session';
import { supabase } from '~/lib/supabase';

export function NewPlaylistDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const { userId, pendingPick, setPendingPick } = useSession();
  const { create, addItem } = usePlaylistMutations(supabase, userId);

  const [name, setName] = useState('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;
    setName('');
    setError(null);
  }, [open]);

  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!name.trim() || !userId) return;
    setError(null);
    try {
      const playlist = await create.mutateAsync(name);
      // The whole point of the pending pick: the listener asked to file a
      // shabad and had no playlist to file it into.
      if (pendingPick) {
        await addItem.mutateAsync({ playlistId: playlist.id, renditionId: pendingPick.id });
        toast.success(`Added “${pendingPick.name}” to ${playlist.name}`);
        setPendingPick(null);
      }
      onOpenChange(false);
    } catch (failure) {
      setError(failure instanceof Error ? failure.message : 'Could not create the playlist');
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>New playlist</DialogTitle>
          {pendingPick ? (
            <DialogDescription>“{pendingPick.name}” goes in once it exists.</DialogDescription>
          ) : null}
        </DialogHeader>

        <form onSubmit={submit} className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <Label htmlFor="playlist-name">Name</Label>
            <Input
              id="playlist-name"
              value={name}
              autoFocus
              onChange={(e) => setName(e.target.value)}
              placeholder="Morning kirtan"
            />
          </div>

          {error ? (
            <p role="alert" className="text-sm text-destructive">
              {error}
            </p>
          ) : null}

          <Button type="submit" disabled={!name.trim() || create.isPending}>
            {create.isPending ? 'Creating…' : 'Create'}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}
