// apps/player/app/components/QueueList.vue
<script setup lang="ts">
/**
 * Up next, wherever it is shown.
 *
 * Two places now: the panel that slides over the desktop bar, and a view inside
 * the full-screen player on a phone. Same list, so it lives here rather than in
 * both — only the frame around it differs, which is what `onClose` decides.
 */
import { X, Play } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { usePlayer, toPlayable } from '~/composables/usePlayer';
import { useQueueSuggestions } from '~/composables/useQueueSuggestions';

/** Close affordance, for the frame that needs one. The full-screen view
 *  switches back with the same toggle that opened it, so it passes nothing. */
const props = defineProps<{ closable?: boolean }>();
const emit = defineEmits<{ close: [] }>();

const player = usePlayer();

// What fills this panel when nobody has queued anything, which is most of the
// time. Suggestions only: tapping one plays it, and nothing starts on its own.
const suggestions = useQueueSuggestions();

/** Plays the tapped suggestion and makes the rest of its group the queue, so
 *  the group behaves like any other list in the app rather than a dead end. */
function playSuggestion(items: any[], index: number) {
  player.playList(items.map(toPlayable), index);
}
</script>

<template>
  <div>
    <div class="mb-2 flex items-center justify-between">
      <p class="text-sm font-semibold text-foreground">Up next</p>
      <!-- Grouped so the title stays hard left rather than the header spacing
           three children across. -->
      <div class="flex items-center gap-1">
        <!-- Absent rather than dimmed when there is nothing to clear. -->
        <Button
          v-if="player.upNext.value.length"
          variant="ghost"
          size="xs"
          class="text-muted-foreground hover:text-foreground"
          @click="player.clearUpNext"
        >
          Clear
        </Button>
        <Button
          v-if="props.closable"
          variant="ghost"
          size="icon-sm"
          class="size-7 text-muted-foreground"
          aria-label="Close up next"
          @click="emit('close')"
        >
          <X class="size-4" />
        </Button>
      </div>
    </div>

    <template v-if="!player.upNext.value.length">
      <p class="pb-3 text-xs text-muted-foreground">Nothing queued.</p>

      <!-- Grouped and headed, so it is legible as "here is what you could play
           next" rather than as a queue that filled itself. -->
      <div
        v-for="group in suggestions.groups.value"
        :key="group.label"
        class="mb-3"
      >
        <p class="px-2 pb-1 text-[11px] font-medium text-muted-foreground">
          {{ group.label }}
        </p>
        <Button
          v-for="(item, i) in group.items"
          :key="item.id"
          variant="ghost"
          class="group h-auto w-full justify-start gap-2.5 px-2 py-1.5 text-left font-normal"
          @click="playSuggestion(group.items, i)"
        >
          <span class="relative size-8 shrink-0">
            <ArtTile
              :name="item.artist ?? item.name"
              :photo="item.artist_photo"
              class="size-8 text-[9px]"
            />
            <span
              class="absolute inset-0 grid place-items-center rounded-md bg-black/55 opacity-0 transition group-hover:opacity-100"
            >
              <Play class="size-3.5 fill-current text-white" />
            </span>
          </span>
          <span class="min-w-0 flex-1">
            <span class="block truncate text-xs text-foreground">{{
              item.name
            }}</span>
            <span class="block truncate text-[11px] text-muted-foreground">{{
              item.artist_display ?? item.artist
            }}</span>
          </span>
        </Button>
      </div>
    </template>
    <Button
      v-for="item in player.upNext.value"
      :key="item.id"
      variant="ghost"
      class="group h-auto w-full justify-start gap-2.5 px-2 py-1.5 text-left font-normal"
      @click="player.playFromQueue(item.id)"
    >
      <!-- Same affordance as a row in a list: the tile is what you click, so on
           hover it says so. -->
      <span class="relative size-8 shrink-0">
        <ArtTile
          :name="item.artist ?? item.title"
          :photo="item.artistPhoto"
          class="size-8 text-[9px]"
        />
        <span
          class="absolute inset-0 grid place-items-center rounded-md bg-black/55 opacity-0 transition group-hover:opacity-100"
        >
          <Play class="size-3.5 fill-current text-white" />
        </span>
      </span>
      <span class="min-w-0 flex-1">
        <span class="block truncate text-xs text-foreground">{{
          item.title
        }}</span>
        <span class="block truncate text-[11px] text-muted-foreground">{{
          item.subtitle
        }}</span>
      </span>
    </Button>
  </div>
</template>

// apps/player/src/components/QueueList.tsx
/**
 * Up next — the real queue when there is one, suggestions when there is not.
 *
 * The queue is empty almost all of the time, so this panel spent its life
 * saying "Nothing queued". The suggestions are deliberately only suggestions:
 * nothing here is queued and nothing plays on its own, because a shabad is
 * often put on for its own sake and continuing unasked is the listener's call.
 */
import { fetchSuggestionGroups } from '@kp/api';
import { upNext, type Playable } from '@kp/core';
import { Button } from '@kp/ui/button';
import { useQuery } from '@tanstack/react-query';
import { Play, X } from 'lucide-react';

import { ArtTile } from '~/components/ArtTile';
import { playerActions, usePlayer } from '~/lib/player';
import { artistPhotoUrl, supabase } from '~/lib/supabase';
import { cn } from '~/lib/utils';

export function QueueList({ className }: { className?: string }) {
  const items = usePlayer((s) => s.items);
  const index = usePlayer((s) => s.index);
  const repeat = usePlayer((s) => s.repeat);
  const current = usePlayer((s) => s.current);

  const queued = upNext({ items, index, repeat });

  const suggestions = useQuery({
    queryKey: ['suggestions', current?.id],
    queryFn: () => fetchSuggestionGroups(supabase, current),
    // Only asked for when the queue has nothing — otherwise this is a request
    // for a panel nobody is looking at.
    enabled: queued.length === 0 && Boolean(current) && !current?.isLive,
    staleTime: 1000 * 60 * 5,
  });

  if (queued.length) {
    return (
      <div className={cn('flex flex-col gap-1', className)}>
        <p className="px-1 text-xs uppercase tracking-wider text-muted-foreground">Up next</p>
        {queued.map((item, i) => (
          <Row
            key={`${item.id}-${i}`}
            item={item}
            onPlay={() => playerActions.playAt(index + 1 + i)}
            onRemove={() => playerActions.removeAt(index + 1 + i)}
          />
        ))}
        <Button
          variant="ghost"
          size="sm"
          onClick={playerActions.clearQueue}
          className="mt-1 self-start text-muted-foreground">
          Clear queue
        </Button>
      </div>
    );
  }

  return (
    <div className={cn('flex flex-col gap-4', className)}>
      {(suggestions.data ?? []).map((group) => (
        <div key={group.label} className="flex flex-col gap-1">
          <p className="px-1 text-xs uppercase tracking-wider text-muted-foreground">
            {group.label}
          </p>
          {group.items.map((item) => (
            <Row key={item.id} item={item} onPlay={() => playerActions.play(item)} />
          ))}
        </div>
      ))}

      {!suggestions.isLoading && !(suggestions.data ?? []).length ? (
        <p className="px-1 py-4 text-sm text-muted-foreground">Nothing queued.</p>
      ) : null}
    </div>
  );
}

function Row({
  item,
  onPlay,
  onRemove,
}: {
  item: Playable;
  onPlay: () => void;
  onRemove?: () => void;
}) {
  return (
    <div className="group flex items-center gap-2 rounded-lg px-1 py-1.5 hover:bg-accent/50">
      <ArtTile
        name={item.artist ?? item.title}
        src={artistPhotoUrl(item.artistPhoto)}
        className="size-8 text-sm"
      />
      <button type="button" onClick={onPlay} className="min-w-0 flex-1 text-left">
        <p className="truncate text-sm">{item.title}</p>
        <p className="truncate text-xs text-muted-foreground">{item.subtitle ?? item.artist}</p>
      </button>
      <Button
        variant="ghost"
        size="icon-sm"
        aria-label={`Play ${item.title}`}
        onClick={onPlay}
        className="opacity-0 group-hover:opacity-100">
        <Play />
      </Button>
      {onRemove ? (
        <Button
          variant="ghost"
          size="icon-sm"
          aria-label={`Remove ${item.title} from the queue`}
          onClick={onRemove}
          className="opacity-0 group-hover:opacity-100">
          <X />
        </Button>
      ) : null}
    </div>
  );
}
