// apps/player/app/components/SeekBar.vue
<script setup lang="ts">
/**
 * The scrubber, for both breakpoints.
 *
 * Mobile used to get a 2px unstyled `<div>` painted to the segment's progress —
 * readable only if you knew to look for it, and impossible to move, so a phone
 * could play a 70-minute set with no way to reach minute 40 of it. This is one
 * control used at both sizes instead: same behaviour on a mouse and a thumb,
 * with the paint thin and the hit area 24px tall, which is what a finger needs.
 *
 * Pointer events rather than a native `<input type="range">` — the pattern
 * admin's TrackTimeline uses. A range input's drag on iOS Safari starts only
 * from the thumb, so a 12px target would be the whole scrubbing story on the
 * platform this is being fixed for; `setPointerCapture` from anywhere on the
 * track behaves identically everywhere. Keyboard and ARIA are then ours to
 * carry, which is what `role="slider"` and `onKey` below are.
 */
import { formatTime } from '~/composables/usePlayer';

const props = defineProps<{
  /** Where playback is, 0–100 across the segment. */
  progress: number;
  /** Seconds into the segment, for the leading label. */
  elapsed: number;
  /** Length of the segment — of the file, when nothing is tagged. */
  total: number;
  disabled?: boolean;
}>();

/** Emitted once per gesture, as a percentage: only the parent knows which
 *  window of which file the segment is, so it does the mapping to seconds. */
const emit = defineEmits<{ seek: [pct: number] }>();

const bar = useTemplateRef<HTMLElement>('bar');

/** Nothing to scrub before the duration is known — a whole file has none until
 *  `loadedmetadata` lands, and a dead control should not look live. */
const inert = computed(() => props.disabled || !(props.total > 0));

/**
 * Where the gesture has dragged to, or null when no gesture is running.
 *
 * The bar follows the finger while it is down, not `timeupdate`: mirroring
 * playback mid-drag would pull the thumb out from under the finger four times a
 * second. It also means the seek is committed once, on release, instead of
 * firing a range request per pointermove.
 */
const draft = ref<number | null>(null);

const pct = computed(() =>
  Math.min(100, Math.max(0, draft.value ?? props.progress))
);

/** The leading label reads the drag while there is one, so a scrub says where
 *  it is going before it goes there. */
const shownElapsed = computed(() =>
  draft.value === null ? props.elapsed : (props.total * draft.value) / 100
);

function pctAt(clientX: number): number {
  const rect = bar.value?.getBoundingClientRect();
  if (!rect?.width) return 0;
  return Math.min(100, Math.max(0, ((clientX - rect.left) / rect.width) * 100));
}

function drag(down: PointerEvent) {
  if (inert.value) return;
  const el = down.currentTarget as HTMLElement;
  // Capture keeps the drag alive once the pointer leaves the 24px band, which
  // a thumb does immediately; `touch-none` on the same element is what stops
  // the page treating the sideways drag as a scroll.
  el.setPointerCapture(down.pointerId);
  draft.value = pctAt(down.clientX);
  const place = (e: PointerEvent) => {
    draft.value = pctAt(e.clientX);
  };
  el.addEventListener('pointermove', place);
  // Fires for pointerup and pointercancel alike, so one listener tears down —
  // and a tap that never moved commits the position it landed on, which is
  // tap-to-seek for free.
  el.addEventListener(
    'lostpointercapture',
    () => {
      el.removeEventListener('pointermove', place);
      const p = draft.value;
      draft.value = null;
      if (p !== null) emit('seek', p);
    },
    { once: true }
  );
}

/** Ten seconds, the step the app's arrow-key shortcuts already use. */
const SEEK_STEP = 10;

function onKey(event: KeyboardEvent) {
  if (inert.value) return;
  const step = (SEEK_STEP / props.total) * 100;
  let next: number | null = null;
  switch (event.key) {
    case 'ArrowRight':
    case 'ArrowUp':
      next = pct.value + step;
      break;
    case 'ArrowLeft':
    case 'ArrowDown':
      next = pct.value - step;
      break;
    case 'Home':
      next = 0;
      break;
    case 'End':
      next = 100;
      break;
  }
  // Everything else still belongs to the transport — space must keep pausing
  // while the scrubber holds focus.
  if (next === null) return;
  event.preventDefault();
  // usePlayerKeys listens on window and treats arrows as a seek too. Without
  // this the press would move the playhead twice.
  event.stopPropagation();
  emit('seek', Math.min(100, Math.max(0, next)));
}
</script>

<template>
  <div class="flex select-none items-center gap-2">
    <span
      class="w-9 shrink-0 text-right text-[11px] tabular-nums text-muted-foreground"
    >
      {{ formatTime(shownElapsed) }}
    </span>

    <!-- The band is the target and the line inside it is the paint: a 4px bar
         is the right weight to read and the wrong one to hit. -->
    <div
      ref="bar"
      class="group relative flex h-6 min-w-0 flex-1 touch-none items-center rounded-full focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
      :class="inert ? 'cursor-default' : 'cursor-pointer'"
      role="slider"
      :tabindex="inert ? -1 : 0"
      :aria-disabled="inert || undefined"
      aria-label="Seek within this shabad"
      aria-valuemin="0"
      aria-valuemax="100"
      :aria-valuenow="Math.round(pct)"
      :aria-valuetext="`${formatTime(shownElapsed)} of ${formatTime(total)}`"
      @pointerdown="drag"
      @keydown="onKey"
    >
      <div
        class="h-1.5 w-full overflow-hidden rounded-full bg-muted transition-[height] md:h-1 md:group-hover:h-1.5"
      >
        <div
          class="h-full rounded-full bg-primary"
          :style="{ width: `${pct}%` }"
        />
      </div>
      <!-- Always drawn rather than revealed on hover: a phone has no hover, and
           the thumb is the part that says the line can be moved at all. -->
      <span
        v-if="!inert"
        class="absolute top-1/2 size-3.5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary shadow-sm transition-transform md:size-3 md:group-hover:scale-125"
        :style="{ left: `${pct}%` }"
      />
    </div>

    <span class="w-9 shrink-0 text-[11px] tabular-nums text-muted-foreground">
      {{ formatTime(total) }}
    </span>
  </div>
</template>

// apps/player/src/components/SeekBar.tsx
/**
 * The scrubber.
 *
 * Reads position with a selector rather than the whole store: this is the one
 * component that genuinely needs 10Hz, and it should be the only thing paying
 * for it.
 *
 * A bar you can drag, not a line you can tap. The first version seeked on
 * pointer-down and listened for nothing after it, so the one gesture everybody
 * brings to a player from every other player — press, drag, watch the clock,
 * let go — jumped once and then ignored the finger. The native app already
 * scrubs; this is the same behaviour with pointer events.
 */
import { progressPct, seekTargetForPct, elapsedIn, segmentTotal } from '@kp/core';
import { useRef, useState } from 'react';

import { playerActions, usePlayer } from '~/lib/player';
import { clock, cn } from '~/lib/utils';

export function SeekBar() {
  const current = usePlayer((s) => s.current);
  const position = usePlayer((s) => s.position);
  const duration = usePlayer((s) => s.duration);
  const track = useRef<HTMLDivElement>(null);
  /** Percentage under the pointer while dragging, or null when not. */
  const [scrub, setScrub] = useState<number | null>(null);

  /**
   * A broadcast has no timeline to scrub and no end to scrub towards, and it
   * already says LIVE beside the title. Nothing is drawn rather than an inert
   * track: a greyed-out bar still claims there is a length to be part-way
   * through. The transport's column holds the height instead, so the bar does
   * not change size when a station starts.
   */
  if (current?.isLive) return null;

  /**
   * While a drag is in progress the bar follows the pointer rather than the
   * playhead, and the clock reads the dragged position. Without that the fill
   * springs back to wherever playback has got to on every status tick, ten
   * times a second, and the drag feels like it is fighting you.
   */
  const pct = scrub ?? progressPct(current, position, duration);
  const elapsed =
    scrub === null ? elapsedIn(current, position) : (scrub / 100) * segmentTotal(current, duration);

  function pctFromPointer(clientX: number): number | null {
    const box = track.current?.getBoundingClientRect();
    if (!box || box.width === 0) return null;
    return Math.min(100, Math.max(0, ((clientX - box.left) / box.width) * 100));
  }

  /**
   * The seek lands on release, not on every move: a drag across a 70-minute
   * file is a few hundred pointer events, and seeking on each one is a few
   * hundred range requests for audio nobody will hear. What the listener is
   * reading during the drag is the clock, and that follows the pointer.
   */
  function commit(clientX: number) {
    const to = pctFromPointer(clientX) ?? scrub;
    if (to !== null) playerActions.seek(seekTargetForPct(current, to, duration));
    setScrub(null);
  }

  return (
    <div className="flex w-full items-center gap-3">
      <span className="w-10 shrink-0 text-right text-xs tabular-nums text-muted-foreground">
        {clock(elapsed)}
      </span>
      <div
        ref={track}
        role="slider"
        tabIndex={0}
        aria-label="Seek"
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuenow={Math.round(pct)}
        // `touch-none`, or a drag on a phone scrolls the page under the finger
        // instead of scrubbing — the gesture the browser assumes by default.
        className="group h-6 flex-1 cursor-pointer touch-none select-none py-2.5"
        onPointerDown={(e) => {
          if (e.button !== 0) return;
          const to = pctFromPointer(e.clientX);
          if (to === null) return;
          // Capture, so the rest of the drag arrives here even when the pointer
          // leaves this 4px-high bar — which it does, immediately, every time.
          e.currentTarget.setPointerCapture(e.pointerId);
          setScrub(to);
        }}
        onPointerMove={(e) => {
          if (scrub === null) return;
          const to = pctFromPointer(e.clientX);
          if (to !== null) setScrub(to);
        }}
        onPointerUp={(e) => {
          if (scrub === null) return;
          commit(e.clientX);
        }}
        // A cancelled pointer is the system taking the gesture away — a phone
        // call, a back-swipe. Nobody asked to seek, so nothing seeks.
        onPointerCancel={() => setScrub(null)}
        onKeyDown={(e) => {
          // Five seconds, the same nudge the arrow keys give everywhere else.
          if (e.key !== 'ArrowRight' && e.key !== 'ArrowLeft') return;
          // The app-wide shortcut nudges by the same five seconds, and with
          // this bar focused both handlers ran: one press, ten seconds. This is
          // the one that belongs to a focused slider, so it takes the key and
          // keeps it — including the scroll the arrow would otherwise cause,
          // which the shortcut used to prevent on this bar's behalf.
          e.preventDefault();
          e.stopPropagation();
          playerActions.seek(position + (e.key === 'ArrowRight' ? 5 : -5));
        }}
      >
        <div className="relative h-1 w-full">
          <div className="h-full w-full overflow-hidden rounded-full bg-muted">
            <div className="h-full rounded-full bg-primary" style={{ width: `${pct}%` }} />
          </div>
          {/* Outside the fill's own bounds, so the rounded overflow that keeps
              the fill's corners clean cannot clip it. It grows under the
              pointer, which is the only feedback a handle this small can give,
              and it is what says the bar is draggable before anyone drags it. */}
          <div
            aria-hidden="true"
            style={{ left: `${pct}%` }}
            className={cn(
              'pointer-events-none absolute top-1/2 size-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary transition-[width,height]',
              'group-hover:size-4 group-focus-visible:size-4',
              scrub !== null && 'size-4'
            )}
          />
        </div>
      </div>
      <span className="w-10 shrink-0 text-xs tabular-nums text-muted-foreground">
        {clock(segmentTotal(current, duration))}
      </span>
    </div>
  );
}
