// apps/admin/src/routes/pending.tsx
/**
 * The review queue.
 *
 * Everything a contributor proposes lands here. Nothing reaches the player
 * until somebody publishes it, which is the only thing the trust ladder gates.
 */
import {
  canPublishRendition,
  deleteRendition,
  setRenditionStatus,
  usePending,
  type PendingRendition,
} from '@kp/api';
import { Badge } from '@kp/ui/badge';
import { Button } from '@kp/ui/button';
import { useQueryClient } from '@tanstack/react-query';
import { Link } from '@tanstack/react-router';
import { Check, Play, Trash2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

import { LoadStatus } from '~/components/LoadStatus';
import { useSession } from '~/lib/session';
import { supabase } from '~/lib/supabase';
import { clock } from '~/lib/utils';

export function PendingRoute() {
  const { session, can } = useSession();
  const query = usePending(supabase, Boolean(session));
  const queryClient = useQueryClient();

  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);

  /**
   * Created in JS rather than rendered, so nothing tears it down on
   * navigation — without this a preview keeps playing after the reviewer has
   * left the page, with no UI left to stop it.
   */
  const audio = useRef<HTMLAudioElement | null>(null);
  useEffect(() => () => audio.current?.pause(), []);

  function preview(row: PendingRendition) {
    if (!row.tracks?.url) return;
    if (!audio.current) audio.current = new Audio();
    audio.current.src = row.tracks.url;
    audio.current.currentTime = Number(row.start_sec);
    void audio.current.play().catch(() => setError('Could not start that preview.'));
  }

  async function run(id: string, work: () => Promise<unknown>) {
    setError(null);
    setBusy(id);
    try {
      await work();
      await queryClient.invalidateQueries({ queryKey: ['pending'] });
      await queryClient.invalidateQueries({ queryKey: ['recordings'] });
      // Rejecting a scan draft also drops the scan's pointers to that shabad,
      // which the tag page would otherwise show from its cache.
      await queryClient.invalidateQueries({ queryKey: ['scan-request'] });
    } catch (failure) {
      setError(failure instanceof Error ? failure.message : 'That did not work.');
    } finally {
      setBusy(null);
    }
  }

  const rows = query.data ?? [];

  return (
    <section className="flex flex-col gap-4">
      <header>
        <h1 className="font-display text-3xl font-semibold">
          Review{' '}
          <span className="text-base font-normal text-muted-foreground">({rows.length})</span>
        </h1>
        <p className="text-sm text-muted-foreground">
          Proposed segments, oldest first. Nothing here is in the player yet.
        </p>
      </header>

      {error ? (
        <p role="alert" className="text-sm text-destructive">
          {error}
        </p>
      ) : null}

      <LoadStatus what="the review queue" queries={[query]} />

      {query.data !== undefined && !rows.length ? (
        <p className="rounded-lg border border-dashed border-border px-4 py-10 text-center text-sm text-muted-foreground">
          Nothing waiting. Every proposed segment has been dealt with.
        </p>
      ) : null}

      <div className="flex flex-col gap-0.5">
        {rows.map((row) => {
          const mine = row.created_by === session?.user.id;
          const publishable = canPublishRendition(
            row,
            { review: can['renditions.review'], publish: can['renditions.publish'] },
            session?.user.id
          );

          return (
            <div
              key={row.id}
              className="flex flex-wrap items-center gap-3 rounded-lg px-3 py-2 hover:bg-accent/50"
            >
              <div className="min-w-0 flex-1">
                <Link
                  to="/tag/$id"
                  params={{ id: row.track_id }}
                  // From review there is no shelf to preserve — the tagger
                  // arrived from a different list entirely. The row itself
                  // rides along, so the page opens on it.
                  search={{ rendition: row.id }}
                  className="truncate text-sm hover:underline"
                >
                  {row.name}
                </Link>
                <p className="truncate text-xs text-muted-foreground">
                  {row.tracks?.artist_dir ?? 'Unknown'}
                  {row.tracks?.date ? ` · ${row.tracks.date}` : ''}
                  {` · ${clock(Number(row.start_sec))}–${clock(Number(row.end_sec))}`}
                  {mine ? ' · yours' : ''}
                </p>
              </div>

              <Badge variant="secondary" className="shrink-0">
                {row.status}
              </Badge>

              <Button
                variant="ghost"
                size="icon-sm"
                aria-label={`Preview ${row.name}`}
                onClick={() => preview(row)}
              >
                <Play />
              </Button>

              {publishable ? (
                <Button
                  size="sm"
                  disabled={busy === row.id}
                  onClick={() =>
                    void run(row.id, () => setRenditionStatus(supabase, row.id, 'published'))
                  }
                >
                  <Check />
                  Publish
                </Button>
              ) : null}

              {can['renditions.delete'] ? (
                <Button
                  variant="ghost"
                  size="icon-sm"
                  aria-label={`Reject ${row.name}`}
                  disabled={busy === row.id}
                  className="text-destructive hover:text-destructive"
                  onClick={() => {
                    // Rejecting throws away someone's listening, so it asks.
                    if (
                      window.confirm(
                        `Reject “${row.name}”? This deletes the draft.${row.source === 'scan' ? " The scanner won't suggest it for this recording again." : ''}`
                      )
                    ) {
                      void run(row.id, () => deleteRendition(supabase, row.id));
                    }
                  }}
                >
                  <Trash2 />
                </Button>
              ) : null}
            </div>
          );
        })}
      </div>

      {/* Said rather than left blank: a contributor who cannot publish should
          know that is a trust level, not a broken page. */}
      {!can['renditions.publish'] && rows.length ? (
        <p className="text-xs text-muted-foreground">
          You can see the queue but not publish from it — that comes with the trust ladder.
        </p>
      ) : null}
    </section>
  );
}

// apps/admin/app/pages/pending.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Check, Trash2, Play } from 'lucide-vue-next';

const supabase = useSupabaseClient();

// Everything a contributor proposes lands here. Nothing reaches the player
// until a reviewer publishes it, which is the only thing the trust ladder gates.
const { data: pending, refresh } = await useAsyncData('pending', async () => {
  const { data } = await supabase
    .from('renditions')
    .select('*, tracks(artist_dir, date, url, raw_filename)')
    .neq('status', 'published')
    .order('created_at', { ascending: true })
    .limit(100);
  return data;
});

// The same three permissions the tagging page asks for, and for the same
// reason: gating this queue on review alone hid the publish button from the
// `trusted` role, whose whole purpose is publishing without reviewing. Reject
// is a delete, which is a third permission again.
const { canReview, canPublish, canDelete } = await useMyPermissions();

const { data: userId } = await useAsyncData('me', async () => {
  const { data } = await supabase.auth.getUser();
  return data.user?.id ?? null;
});

const canPublishRow = (s: any) =>
  canPublishRendition(
    s,
    { canReview: canReview.value, canPublish: canPublish.value },
    userId.value
  );

const error = ref('');
const audio = ref<HTMLAudioElement | null>(null);

// Created in JS rather than bound to the template, so nothing tears it down
// on navigation — without this a preview keeps playing after the reviewer has
// left the page, with no UI left to stop it.
onUnmounted(() => audio.value?.pause());
function preview(s: any) {
  if (!audio.value) audio.value = new Audio();
  audio.value.src = s.tracks.url;
  audio.value.currentTime = Number(s.start_sec);
  void audio.value.play();
}

async function publish(s: any) {
  error.value = '';
  // `select('id')` is what makes a refused write visible: RLS filters rows out
  // of an UPDATE rather than rejecting it, so without asking for the changed
  // rows back this returns 204 with no error and the row quietly stays put.
  const { data, error: updateError } = await supabase
    .from('renditions')
    .update({ status: 'published' })
    .eq('id', s.id)
    .select('id');
  if (updateError) error.value = updateError.message;
  else if (!data?.length) error.value = 'Not permitted to publish that one.';
  await refresh();
}
async function reject(s: any) {
  error.value = '';
  // Same silent-refusal trap as publish: a DELETE that RLS declines returns
  // no error and no rows.
  const { data, error: deleteError } = await supabase
    .from('renditions')
    .delete()
    .eq('id', s.id)
    .select('id');
  if (deleteError) error.value = deleteError.message;
  else if (!data?.length) error.value = 'Not permitted to reject that one.';
  await refresh();
}
function fmt(v: number) {
  const m = Math.floor(v / 60),
    sec = Math.floor(v % 60);
  return `${m}:${String(sec).padStart(2, '0')}`;
}
</script>

<template>
  <div>
    <h1 class="mb-1 text-xl font-semibold">Review</h1>
    <p class="mb-5 text-sm text-muted-foreground">
      {{ pending?.length ?? 0 }} segment{{ pending?.length === 1 ? '' : 's' }}
      waiting. Publishing makes them visible in the player.
    </p>

    <p
      v-if="!canPublish"
      class="rounded-md border border-border p-4 text-sm text-muted-foreground"
    >
      Your account can propose segments but not publish them. A reviewer will
      approve your work.
    </p>

    <p v-if="error" class="mb-2 text-xs text-amber-400">{{ error }}</p>

    <!-- The row is a link into the tagging workbench, opened on this very
         rendition: reviewing means checking boundaries and the shabad link,
         which only that page can do. The buttons inside stop the click from
         bubbling to the link, so preview and publish stay one click too. -->
    <NuxtLink
      v-for="s in pending ?? []"
      :key="s.id"
      :to="`/tag/${s.track_id}?rendition=${s.id}`"
      class="flex items-center gap-3 rounded-md px-3 py-2.5 transition hover:bg-accent"
    >
      <Button
        variant="ghost"
        size="icon-sm"
        class="size-7 text-muted-foreground"
        title="Preview from the start boundary"
        :aria-label="`Preview ${s.name} from its start boundary`"
        @click.stop.prevent="preview(s)"
      >
        <Play class="size-3.5" />
      </Button>
      <span class="min-w-0 flex-1">
        <span class="block truncate text-sm">{{ s.name }}</span>
        <span class="block truncate text-[11px] text-muted-foreground">
          {{
            [
              s.tracks?.artist_dir,
              s.tracks?.date,
              s.raag,
              // 'manual' is the norm, so only the exception is worth a word —
              // a scan suggestion earns a closer look at its boundaries.
              s.source !== 'manual' ? s.source : null,
            ]
              .filter(Boolean)
              .join(' · ')
          }}
        </span>
      </span>
      <span class="shrink-0 text-xs tabular-nums text-muted-foreground">
        {{ fmt(Number(s.start_sec)) }}–{{ fmt(Number(s.end_sec)) }}
      </span>
      <Badge variant="secondary" class="shrink-0 rounded-full text-[11px]">
        {{ s.status }}
      </Badge>
      <!-- Offered per row and per right, so neither button can lead to a write
           RLS would filter out: publishing somebody else's draft needs review,
           and rejecting anything needs the delete permission. -->
      <Button
        v-if="canPublishRow(s)"
        variant="ghost"
        size="icon-sm"
        class="size-7 text-emerald-400"
        title="Publish"
        :aria-label="`Publish ${s.name}`"
        @click.stop.prevent="publish(s)"
      >
        <Check class="size-4" />
      </Button>
      <Button
        v-if="canDelete"
        variant="ghost"
        size="icon-sm"
        class="size-7 text-muted-foreground hover:text-destructive"
        title="Reject"
        :aria-label="`Reject ${s.name}`"
        @click.stop.prevent="reject(s)"
      >
        <Trash2 class="size-3.5" />
      </Button>
    </NuxtLink>

    <p
      v-if="!pending?.length"
      class="py-16 text-center text-sm text-muted-foreground"
    >
      Nothing waiting for review.
    </p>
  </div>
</template>
